import type { NarrativeResult } from "../types";

interface NarrativeCardProps {
  narrative: NarrativeResult;
}

export function NarrativeCard({ narrative }: NarrativeCardProps) {
  return (
    <div className="rounded-lg border border-slate-200 bg-white p-5">
      <div className="mb-3 flex items-center justify-between">
        <h3 className="text-sm font-semibold uppercase tracking-wide text-slate-500">Underwriter Assessment</h3>
        <span
          className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${
            narrative.source === "anthropic"
              ? "bg-teal-50 text-teal-700"
              : "bg-slate-100 text-slate-500"
          }`}
        >
          {narrative.source === "anthropic" ? "Generated by Claude" : "Local fallback"}
        </span>
      </div>

      <div className="space-y-3">
        <div className="flex gap-3 rounded-md bg-green-50 p-3">
          <span className="mt-0.5 flex h-6 w-6 flex-none items-center justify-center rounded-full bg-green-600 text-xs font-bold text-white">
            +
          </span>
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-green-700">Key Strength</p>
            <p className="mt-0.5 text-sm text-slate-800">{narrative.strength}</p>
          </div>
        </div>

        <div className="flex gap-3 rounded-md bg-orange-50 p-3">
          <span className="mt-0.5 flex h-6 w-6 flex-none items-center justify-center rounded-full bg-orange-600 text-xs font-bold text-white">
            !
          </span>
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-orange-700">Key Risk</p>
            <p className="mt-0.5 text-sm text-slate-800">{narrative.risk}</p>
          </div>
        </div>

        <div className="flex gap-3 rounded-md bg-blue-50 p-3">
          <span className="mt-0.5 flex h-6 w-6 flex-none items-center justify-center rounded-full bg-blue-600 text-xs font-bold text-white">
            i
          </span>
          <div className="flex-1">
            <p className="text-xs font-semibold uppercase tracking-wide text-blue-700">
              Recommendations to Improve Score
            </p>
            <ul className="mt-1 list-disc space-y-1 pl-4 text-sm text-slate-800">
              {narrative.improvement_tips.map((tip, i) => (
                <li key={i}>{tip}</li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
