import PDFDocument from "pdfkit";
import type {
  MLRiskResult,
  MSMEProfileMeta,
  NarrativeResult,
  NormalizedMSMEData,
  ScoreBand,
  ScoreResult,
} from "../types/index.js";

const ML_BAND_COLORS: Record<string, string> = {
  Low: "#15803d",
  Moderate: "#65a30d",
  Elevated: "#f97316",
  High: "#dc2626",
};

const BAND_COLORS: Record<ScoreBand, string> = {
  Poor: "#dc2626",
  Bad: "#f97316",
  Average: "#eab308",
  Good: "#65a30d",
  Excellent: "#15803d",
};

const RECOMMENDED_ACTION: Record<ScoreBand, string> = {
  Excellent: "Recommend approval.",
  Good: "Recommend approval.",
  Average: "Recommend conditional approval with monitoring.",
  Bad: "Recommend decline or further manual review.",
  Poor: "Recommend decline or further manual review.",
};

function formatDate(d: Date): string {
  return d.toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" });
}

function hr(doc: PDFKit.PDFDocument, width: number): void {
  const y = doc.y;
  doc.moveTo(doc.x, y).lineTo(doc.x + width, y).strokeColor("#e2e8f0").lineWidth(1).stroke();
}

function sectionTitle(doc: PDFKit.PDFDocument, title: string): void {
  doc.moveDown(0.6);
  doc.font("Helvetica-Bold").fontSize(12).fillColor("#0f172a").text(title.toUpperCase(), { characterSpacing: 0.3 });
  doc.moveDown(0.3);
}

function labeledParagraph(doc: PDFKit.PDFDocument, label: string, text: string, color: string): void {
  doc.font("Helvetica-Bold").fontSize(8.5).fillColor(color).text(label.toUpperCase(), { characterSpacing: 0.3 });
  doc.font("Helvetica").fontSize(10).fillColor("#1f2937").text(text);
  doc.moveDown(0.5);
}

function flagList(doc: PDFKit.PDFDocument, label: string, flags: string[], color: string): void {
  doc
    .font("Helvetica-Bold")
    .fontSize(8.5)
    .fillColor(color)
    .text(`${label.toUpperCase()} (${flags.length})`, { characterSpacing: 0.3 });
  if (flags.length === 0) {
    doc.font("Helvetica-Oblique").fontSize(9).fillColor("#94a3b8").text("None flagged.");
  } else {
    doc.font("Helvetica").fontSize(9.5).fillColor("#1f2937");
    flags.forEach((f) => doc.text(`\u2022  ${f}`, { indent: 6 }));
  }
  doc.moveDown(0.5);
}

function renderPillarTable(doc: PDFKit.PDFDocument, score: ScoreResult, pageWidth: number): void {
  const columns = [
    { header: "Pillar", width: pageWidth * 0.4 },
    { header: "Score", width: pageWidth * 0.2 },
    { header: "Weight", width: pageWidth * 0.2 },
    { header: "Applied", width: pageWidth * 0.2 },
  ];
  const startX = doc.x;
  let y = doc.y;

  doc.font("Helvetica-Bold").fontSize(8.5).fillColor("#64748b");
  let x = startX;
  columns.forEach((col) => {
    doc.text(col.header.toUpperCase(), x, y, { width: col.width, characterSpacing: 0.3 });
    x += col.width;
  });
  y += 16;
  doc.moveTo(startX, y).lineTo(startX + pageWidth, y).strokeColor("#e2e8f0").lineWidth(1).stroke();
  y += 8;

  score.pillars.forEach((p) => {
    x = startX;
    const textColor = p.applied ? "#1f2937" : "#94a3b8";
    doc.font("Helvetica-Bold").fontSize(10).fillColor(textColor).text(p.label, x, y, { width: columns[0].width });
    x += columns[0].width;
    doc.font("Helvetica").fontSize(10).fillColor(textColor).text(p.applied ? `${p.score}/100` : "\u2014", x, y, {
      width: columns[1].width,
    });
    x += columns[1].width;
    doc.text(`${Math.round(p.weight * 100)}%`, x, y, { width: columns[2].width });
    x += columns[2].width;
    doc.text(p.applied ? "Yes" : "No (reweighted)", x, y, { width: columns[3].width });
    y += 22;
  });

  doc.x = startX;
  doc.y = y + 6;

  if (score.reweighted && score.reweight_note) {
    doc.font("Helvetica-Oblique").fontSize(8.5).fillColor("#92400e").text(score.reweight_note);
  }
}

function addFooter(doc: PDFKit.PDFDocument, normalized: NormalizedMSMEData, pageWidth: number): void {
  doc.moveDown(1);
  hr(doc, pageWidth);
  doc.moveDown(0.4);
  doc.font("Helvetica").fontSize(8).fillColor("#94a3b8");
  doc.text(`Data sources used: ${normalized.data_sources_available.join(", ") || "None available"}.`);
  doc.text(`Assessment based on ${normalized.months_of_data_available} month(s) of observed data.`);
  doc.moveDown(0.3);
  doc.text(
    "This memo is generated by an automated alternate-data credit health assessment model (GST, UPI, Account " +
      "Aggregator, and EPFO signals). It is intended to support, not replace, manual underwriting judgment."
  );
}

function renderMLRiskSection(doc: PDFKit.PDFDocument, mlRisk: MLRiskResult, pageWidth: number): void {
  sectionTitle(doc, "ML Risk Layer — Probability of Default (XGBoost + SHAP)");

  if (!mlRisk.available || mlRisk.probability_of_default_pct === null) {
    doc
      .font("Helvetica-Oblique")
      .fontSize(9.5)
      .fillColor("#94a3b8")
      .text(`ML risk service was unavailable for this assessment (${mlRisk.fallback_reason ?? "unknown reason"}). Recommendation relies on the rule-based score above only.`);
    doc.moveDown(0.5);
    return;
  }

  const bandColor = ML_BAND_COLORS[mlRisk.risk_band ?? "Moderate"] ?? "#64748b";
  const startY = doc.y;
  doc.font("Helvetica-Bold").fontSize(22).fillColor("#0f172a").text(`${mlRisk.probability_of_default_pct}% PD`, doc.x, startY, {
    continued: false,
  });
  doc.font("Helvetica-Bold").fontSize(11).fillColor(bandColor).text(`${(mlRisk.risk_band ?? "").toUpperCase()} ML RISK BAND`, {
    characterSpacing: 0.5,
  });
  doc.font("Helvetica").fontSize(9).fillColor("#64748b").text(`Model confidence: ${mlRisk.confidence_pct}%  |  Model: ${mlRisk.model_version}`);
  doc.moveDown(0.4);

  doc.font("Helvetica-Bold").fontSize(8.5).fillColor("#b91c1c").text("TOP RISK-INCREASING FACTORS (SHAP)", { characterSpacing: 0.3 });
  doc.font("Helvetica").fontSize(9.5).fillColor("#1f2937");
  if (mlRisk.top_risk_increasing_features.length === 0) {
    doc.text("None identified.");
  } else {
    mlRisk.top_risk_increasing_features.forEach((f) => doc.text(`\u2022  ${f.feature}`, { indent: 6 }));
  }
  doc.moveDown(0.3);

  doc.font("Helvetica-Bold").fontSize(8.5).fillColor("#15803d").text("TOP RISK-REDUCING FACTORS (SHAP)", { characterSpacing: 0.3 });
  doc.font("Helvetica").fontSize(9.5).fillColor("#1f2937");
  if (mlRisk.top_risk_reducing_features.length === 0) {
    doc.text("None identified.");
  } else {
    mlRisk.top_risk_reducing_features.forEach((f) => doc.text(`\u2022  ${f.feature}`, { indent: 6 }));
  }
  doc.moveDown(0.4);

  doc
    .font("Helvetica-Oblique")
    .fontSize(7.5)
    .fillColor("#94a3b8")
    .text(
      "Demonstration model trained on a public bureau-style dataset (Give Me Some Credit, Kaggle) with alt-data " +
        "translated into its feature space via a documented heuristic bridge. Not trained on IDBI's historical " +
        "repayment or alternate-data records. In production this model would be retrained directly on that data.",
      { width: pageWidth }
    );
  doc.moveDown(0.3);
}

/**
 * Builds a formatted, bank-ready credit assessment memo PDF for a single
 * MSME. Reads only from the already-computed profile/normalized/score/
 * narrative objects produced by the existing pipeline — no scoring logic
 * lives here.
 */
export function buildCreditMemoDoc(
  profile: MSMEProfileMeta,
  normalized: NormalizedMSMEData,
  score: ScoreResult,
  narrative: NarrativeResult,
  mlRisk: MLRiskResult
): PDFKit.PDFDocument {
  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 56, bottom: 56, left: 56, right: 56 },
    info: {
      Title: `Credit Assessment Memo - ${profile.name}`,
      Author: "MSME Financial Health Card",
    },
  });

  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const bandColor = BAND_COLORS[score.band];

  // ---- Header ----
  doc.fillColor("#0f766e").font("Helvetica-Bold").fontSize(9).text("MSME FINANCIAL HEALTH CARD", {
    characterSpacing: 1,
  });
  doc.moveDown(0.15);
  doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(20).text("Credit Assessment Memo");
  doc.moveDown(0.1);
  doc.fillColor("#334155").font("Helvetica-Bold").fontSize(12).text(profile.name);
  doc.fillColor("#64748b").font("Helvetica").fontSize(10).text(profile.businessType);
  doc.text(`Generated: ${formatDate(new Date())}`);

  doc.moveDown(0.6);
  hr(doc, pageWidth);

  // ---- Composite score + band ----
  sectionTitle(doc, "Composite Score & Risk Band");
  doc.font("Helvetica-Bold").fontSize(30).fillColor("#0f172a").text(`${score.composite_score.toFixed(1)} / 100`);
  doc.font("Helvetica-Bold").fontSize(13).fillColor(bandColor).text(`${score.band.toUpperCase()} BAND`, {
    characterSpacing: 0.5,
  });

  // ---- Pillar breakdown table ----
  sectionTitle(doc, "4-Pillar Score Breakdown");
  renderPillarTable(doc, score, pageWidth);

  // ---- ML Risk Layer ----
  renderMLRiskSection(doc, mlRisk, pageWidth);

  // ---- AI Narrative ----
  sectionTitle(doc, "AI Narrative (Underwriter Assessment)");
  labeledParagraph(doc, "Key Strength", narrative.strength, "#15803d");
  labeledParagraph(doc, "Key Risk", narrative.risk, "#c2410c");
  doc.font("Helvetica-Bold").fontSize(8.5).fillColor("#1d4ed8").text("IMPROVEMENT TIPS", { characterSpacing: 0.3 });
  doc.font("Helvetica").fontSize(10).fillColor("#1f2937");
  narrative.improvement_tips.forEach((tip) => doc.text(`\u2022  ${tip}`, { indent: 6 }));

  // ---- Risk & Strength flags ----
  sectionTitle(doc, "Risk & Strength Flags");
  flagList(doc, "Strengths", score.strength_flags, "#15803d");
  flagList(doc, "Risks", score.risk_flags, "#b91c1c");

  // ---- Recommended action ----
  sectionTitle(doc, "Recommended Action");
  const actionY = doc.y;
  doc.rect(doc.x, actionY, 4, 22).fill(bandColor);
  doc.font("Helvetica-Bold").fontSize(12).fillColor(bandColor).text(RECOMMENDED_ACTION[score.band], doc.x + 14, actionY + 3, {
    width: pageWidth - 14,
  });
  doc.x = doc.page.margins.left;
  doc.y = actionY + 30;

  // ---- Footer ----
  addFooter(doc, normalized, pageWidth);

  return doc;
}
